package com.huhu.algorithm.learn.solution.n2156;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

abstract class SolutionTest {

    Solution solution;

    abstract Solution getSolution();

    @BeforeEach
    void setup() {
        solution = getSolution();
    }

    @Test
    void testA() {
        assertEquals("ee", solution.subStrHash("leetcode", 7, 20, 2, 0));
    }

    @Test
    void testB() {
        assertEquals("fbx", solution.subStrHash("fbxzaad", 31, 100, 3, 32));
    }

    @Test
    void testC() {
        assertEquals("xqgfatvtlwnnkxipmipcpqwbxihxblaplpfckvxti",
                solution.subStrHash("xqgfatvtlwnnkxipmipcpqwbxihxblaplpfckvxtihonijhtezdnkjmmk",
                        22, 51, 41, 9));
    }

    @Test
    void testD() {
        assertEquals("ocqncptbrnhwpsnimqvujjpsiyuiodmfnyzsamjcggkugmlshelzknuthkytvmjrnzrvvmxfzblbzuoustjmhwenaoyprlhcibjajmvdlfepwhmwpqwmrlewfxdpkrmjlssiwoufzqhrivpiyuolyhseivunenoominnvbjuvyblvrkcbcygyliysxlnafzzvacvirrsmrkbletmqiydawojdenvnmumxkbjmjopruaemritneknfqkscenarawzkmehzveykdccvqtgzknvdcijbsaqhhxxrxzsxrfbhhsqhligwflccbrzjdhasjozymzihxsqkpekuuhpmaorlommxkxnjlblpmgtaectqnzhnwxiaqopjcwybbqjylhuuujsnvmunaynqcdabsqrtepcxewpmrajbbfholnyidlecbqvarfhugonofghlagnhtbdcdleamhpiloecmqcofksunftncqjdnmkhldprdahaphculctuyfxfropofbrzdhqscqruoloyzwpwisdyvjqawvzmgxytrxkcpglhphgzhuyajyqvchbhsauabqswlhbekkrffyeqeylptpgesfbrzbwumeiilekjkcbyfayoqhqvnwfxhmmquwuqcqtnjsoumeefjplxiniqpjrlicziyqiympaexoehobealpuomarbnebsjskiadtemneensrmimcffkdhflxhhtwrhltbuofvpxfrhqoiavbgqxtvromiynreddqnbbqpfqgpureukdkoacgixcgbxgtluxhtflqditmhhkslmmcyfayivkhxcaqueynuiojbmfimwdcjjabecplbmodjsyyfilrdkrjxckjtmeeljrefxbogtqgrkaymvmtwdmfkmhnwunruijwnsqfnjoqtnaolvqqsaxmnrdanyjekwzurwpbsbyfyrurwgpzdbyjavptyapczddgujxkcqdfqthpwpgatdtaqokydxdpkdbwlffqwcbuojljgtniksoencypbengvnjiuzpbbwfrfqlfrotebmznspqbmveeuyjpgjncrdkddzrzsvgqvgkaqjerfovrpnohawpblwmdmczorsieudgrhqqcqigraepfnffkdragweuebwepdsfahdjpkfovtsvuhclnjqepomhgpqbkdhvfbvxlvzzrpxajebbqndtkboquoeizaczsutjsmmqkpbdmezxmurnknwnakrjrcidfrgmlyooseuppeyrckcndwbozgbjgpzoebugffqjbavbitpvcjycpbxkdjhwzhhttjmprqbajbmxatvysrldmzvfabimdqxvlowwxxcvtouyfzqvxw",
                solution.subStrHash("nllfkdlnitnguajnmbbdltcioefrijhvmvgxyiftiljrwkckqumtvphowkualkvimibyzmxvoclhvmtxcejxhqlsarevbazxafueoezgxhehpxvlcjtgftwsyglvcrrskxxwyidzbngfgooblnldjwmjebbifnkmtxupmtygonasoocymrgqmdzewljpqvoyoswwnibvfbjmgaiteauhegkolvquajfpnzzpwzsphxciwajdlqvegydbligcjaxdziuepwclcuxiilezjschojvzpgcuyhgqqkvxjhspkxhdncpvvfdjhybyuxgylaozdmkhtzqyxsmsjertvyqqxwhprsuolzuhzsfwqoaixwxncdtctcgjxmowvizzsfzsvfuodzxzhzorkrefcjocphojbncedlbvnzwregivjfnrymxwrrqrkevvdmedtlfyzeouxibxbyircumgizdncvxfyxdmltibbocqncptbrnhwpsnimqvujjpsiyuiodmfnyzsamjcggkugmlshelzknuthkytvmjrnzrvvmxfzblbzuoustjmhwenaoyprlhcibjajmvdlfepwhmwpqwmrlewfxdpkrmjlssiwoufzqhrivpiyuolyhseivunenoominnvbjuvyblvrkcbcygyliysxlnafzzvacvirrsmrkbletmqiydawojdenvnmumxkbjmjopruaemritneknfqkscenarawzkmehzveykdccvqtgzknvdcijbsaqhhxxrxzsxrfbhhsqhligwflccbrzjdhasjozymzihxsqkpekuuhpmaorlommxkxnjlblpmgtaectqnzhnwxiaqopjcwybbqjylhuuujsnvmunaynqcdabsqrtepcxewpmrajbbfholnyidlecbqvarfhugonofghlagnhtbdcdleamhpiloecmqcofksunftncqjdnmkhldprdahaphculctuyfxfropofbrzdhqscqruoloyzwpwisdyvjqawvzmgxytrxkcpglhphgzhuyajyqvchbhsauabqswlhbekkrffyeqeylptpgesfbrzbwumeiilekjkcbyfayoqhqvnwfxhmmquwuqcqtnjsoumeefjplxiniqpjrlicziyqiympaexoehobealpuomarbnebsjskiadtemneensrmimcffkdhflxhhtwrhltbuofvpxfrhqoiavbgqxtvromiynreddqnbbqpfqgpureukdkoacgixcgbxgtluxhtflqditmhhkslmmcyfayivkhxcaqueynuiojbmfimwdcjjabecplbmodjsyyfilrdkrjxckjtmeeljrefxbogtqgrkaymvmtwdmfkmhnwunruijwnsqfnjoqtnaolvqqsaxmnrdanyjekwzurwpbsbyfyrurwgpzdbyjavptyapczddgujxkcqdfqthpwpgatdtaqokydxdpkdbwlffqwcbuojljgtniksoencypbengvnjiuzpbbwfrfqlfrotebmznspqbmveeuyjpgjncrdkddzrzsvgqvgkaqjerfovrpnohawpblwmdmczorsieudgrhqqcqigraepfnffkdragweuebwepdsfahdjpkfovtsvuhclnjqepomhgpqbkdhvfbvxlvzzrpxajebbqndtkboquoeizaczsutjsmmqkpbdmezxmurnknwnakrjrcidfrgmlyooseuppeyrckcndwbozgbjgpzoebugffqjbavbitpvcjycpbxkdjhwzhhttjmprqbajbmxatvysrldmzvfabimdqxvlowwxxcvtouyfzqvxwbduxgdprhiuuvwgxwwecdbxkrhknkmmehxwpnzfomdegpkunbszvzlpakqwzlwzmodzllozbgjwhlzbrjjzfqrhbhuiqwwvfgikenxzfvmunvjmwxxsmycynszcgcjziokxcoqxerdlimtxivuxoiolccnqgegfryyrzaorivaumudmemtspbrmsmisjcvfxxgtlejcohvnlsbikcbdbbnhfenwqptcbuuidtncaldkayubpwyqvvlulhhxxxdcpnekqmigmystawscfmcuqijztxajndjtpjhgvfcmrtzjtzxtaigboynrgpajnnnuktovqmo",
                        97937, 57231, 1357, 42543));
    }

}